"""added score to scored_game model

Revision ID: d2d32f847667
Revises: e482db435c60
Create Date: 2022-02-11 10:35:52.256925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d32f847667'
down_revision = 'e482db435c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scored__game', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scored__game', 'score')
    # ### end Alembic commands ###
